### PR TITLE
Generate stubs for WooCommerce 6.1.0

### PR DESCRIPTION
**Pull request by thejamescollins**
Generated by extracting https://downloads.wordpress.org/plugin/woocommerce.6.1.0.zip to `source/woocommerce`.

This is necessary because WooCommerce's package on Packagist is broken and not available.

See #12

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you James for your work.
#13
Please continue in OM4/woocommerce-stubs as this project is Composer based.
Currently CI is not able to verify commits.
I think Composer packaging is a low priority for the WC Team as barely anyone is installing WC with Composer.

**Comment by szepeviktor** [comment]
It all began with WC 5.9 ...

**Comment by szepeviktor** [comment]
And there is https://github.com/woocommerce/woocommerce/issues/30027 ...

We lack rocket scientists and brain surgeons!!

**Comment by szepeviktor** [comment]
About the release process: in WC releases two different commits may get the same tag :(
Everything is highly unstable.

**Comment by thejamescollins** [comment]
Thanks @szepeviktor, we will use our own fork until WooCommerce fix their composer package.

Feel free to have a read of https://github.com/woocommerce/woocommerce/issues/31475#issuecomment-1004345153 in case you haven't seen it already  - WooCommerce core plan to fix their broken composer package "in the new year" so hopefully it happens soon.

**Comment by szepeviktor** [comment]
Please look only here: https://packagist.org/packages/woocommerce/woocommerce/stats = lack of driving force.

**Pull request closed without merging**
