### PR TITLE
Add missing Action Scheduler stubs

### PR DESCRIPTION
**Pull request by the-csaba**
Hi there

I spotted that the Action Scheduler classes are missing from the `woocommerce-packages-stubs.php` file.

Here is a naive attempt to fix.

Unfortunately, they not following the same directory structure than the others.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Köszönöm @om4csaba !

1. in this type of case I always start a PR upstream, see the above linked issue
1. deprecated code is not included in stubs, it is really old: https://github.com/woocommerce/action-scheduler/tree/master/deprecated - and see WP stubs' finder pls
1. Could you remove 1 indentation from `->append(` on?

**Comment by szepeviktor** [comment]
Thank you.

**Comment by the-csaba** [comment]
Szívesen :)

This Action Scheduler package is a mess. There are classes extending deprecated and external class, like the `ActionScheduler_WPCLI_Scheduler_command` and the `Migration_Command` both extending `WP_CLI_Command`

Would make sense tackling in a separate repo instead?

**Comment by szepeviktor** [comment]
Oh! Thank you for the info!
Please exclude those two.

**Comment by szepeviktor** [comment]
It should work this way:

```php
<?php

require 'wordpress-stubs.php';
require 'woocommerce-stubs.php';
require 'woocommerce-packages-stubs.php';
```

Please run the above: `php a.php`

**Comment by szepeviktor** [comment]
Oh Noooooooooooooo!

We need **all** deprecated classes.

**Comment by the-csaba** [comment]
I fiddling with this:

```php
<?php

return \StubsGenerator\Finder::create()
    ->in([
        'source/woocommerce/packages/*/src',
        'source/woocommerce/packages/action-scheduler/classes',
        'source/woocommerce/packages/action-scheduler/deprecated',
        ])
    ->append(
        \StubsGenerator\Finder::create()
            ->files()
            ->depth('< 1')
            ->name('functions.php')
            ->in(['source/woocommerce/packages/action-scheduler'])
    )
    // Exclude command classes as is uses the wp-cli package.
    ->notPath('WP_CLI')
    ->sortByName()
;
```
But the result only only changes in the order, not adding more classess.

**Comment by szepeviktor** [comment]
Thank you!

The only thing we need to tackle:
```
PHP Warning:  Declaration of Automattic\WooCommerce\Admin\Overrides\ThemeUpgraderSkin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in /home/viktor/src/woocommerce-stubs/woocommerce-packages-stubs.php on line 12684
```

**Comment by szepeviktor** [comment]
My only weapon is a dirty hack:

```
sed -e 's#^\s*public function feedback(\$string#&, ...$args#' -i woocommerce-packages-stubs.php
```

**Comment by the-csaba** [comment]
That would be great!

Meanwhile, I found out there are some function declarations missing from the `woocommerce-admin` package. 

The put into the `includes` dir...

Should we tackle this as well, or you want a separate pull?

**Comment by szepeviktor** [comment]
> Meanwhile, I found out there are some function declarations missing from the `woocommerce-admin` package.

- includes/core-functions.php
- includes/page-controller-functions.php

Would you add more? Why?

**Comment by the-csaba** [comment]
> Would you add more? Why?

I need the `wc_admin_connect_page` function, and probably others as well

See: https://woocommerce.wordpress.com/2020/02/27/integrating-the-new-woocommerce-navigation-bar/

**Comment by szepeviktor** [comment]
Okay. Do you have a nicer solution than 3×`->append(`?

**Comment by the-csaba** [comment]
I think I have :)

See https://github.com/php-stubs/woocommerce-stubs/pull/2

**Pull request merged**
